### ISSUE TITLE
Sharding support

### ISSUE THREAD

**Issue by pizzafox** [T0TProduction/BLAPI#2]
Currently BLAPI doesn't have any code for sharding support. Will there ever be support to send shards along with their server counts to supported listings?

**Comment by T0TProduction** [comment]
Since we're using the metalist for posting by default and they don't support sharding *yet*, it will indeed come in the future.
Manual posting uses their bot list API structure too, so naturally, that does not include sharded posting. 
As they add it, we will do so too. 

TL;DR: Not yet, but certainly will!

**Comment by T0TProduction** [comment]
Sharding is now added via metalists API, full support with manual posting coming soon™
